name: Send message to Telegram
description: Send message to Telegram
inputs:
  token:
    description: Token for Telegram Bot
    required: true
  chat_id:
    description: ID of Telegram Chat
    required: true
  chat_thread_id:
    description: ID of Telegram chat
    required: true
  message:
    description: Text for message
    required: true
  host:
    description: Telegram host
    required: false
    default: "api.telegram.org"
  convert_markdown:
    description: Convert github markdown to telegram markdown
    required: false
    default: false
  issue_tracker_url:
    description: "URL to issue tracker. Example: https://my-project.atlassian.net/browse"
    required: false

outputs:
  message_id:
    description: "ID of sent message"

branding:
  icon: 'message-square'
  color: 'blue'
runs:
  using: docker
  image: docker://ghcr.io/ci-space/notify-telegram:v0.3.0
