name: Send message to Telegram
description: Send message to Telegram
inputs:
  token:
    description: telegram token
    required: true
  chat_id:
    description: telegram chat id
    required: true
  chat_thread_id:
    description: telegram chat thread id
    required: true
  message:
    description: message
    required: true
  host:
    description: telegram host
    required: false
    default: "api.telegram.org"
  convert_markdown:
    description: convert github markdown to telegram markdown
    required: false
    default: false
  issue_tracker_url:
    description: "URL to issue tracker. Example: https://my-project.atlassian.net/browse"
    required: false

branding:
  icon: 'message-square'
  color: 'blue'
runs:
  using: docker
  image: docker://ghcr.io/ci-space/notify-telegram:v0.2.1
